const quotes = [
    {author: "John F. Kennedy", quote: "Those who dare to fail miserably can achieve greatly."}, 
    {author: "Mary Pickford", quote: "If you have made mistakes, there is always another chance for you. You may have a fresh start any moment you choose."}, 
    {author: "Edmond Rostand", quote: "A man is not old as long as he is seeking something."}, 
    {author: "Buddha", quote: "Happiness comes when your work and words are of benefit to yourself and others."}, 
    {author: "Eknath Easwaran", quote: "Through meditation and by giving full attention to one thing at a time, we can learn to direct attention where we choose."}, 
    {author: "Benjamin Franklin", quote: "Without freedom of thought, there can be no such thing as wisdom - and no such thing as public liberty without freedom of speech."}, 
    {author: "Jack Dixon", quote: "If you focus on results, you will never change. If you focus on change, you will get results."}, 
    {author: "Elizabeth Browning", quote: "Light tomorrow with today!"}, 
    {author: "Paramahansa Yogananda", quote: "There is a magnet in your heart that will attract true friends. That magnet is unselfishness, thinking of others first; when you learn to live for others, they will live for you."}, 
    {author: "Barack Obama", quote: "Change will not come if we wait for some other person or some other time. We are the ones we've been waiting for. We are the change that we seek."}, 
    {author: "Arthur M. Schlesinger Jr.", quote: "Science and technology revolutionize our lives, but memory, tradition and myth frame our response."}, 
    {author: "Confucius", quote: "It does not matter how slowly you go as long as you do not stop."}, 
    {author: "Napoleon", quote: "The best cure for the body is a quiet mind."}, 
    {author: "Richard Bach", quote: "Strong beliefs win strong men, and then make them stronger."}, 
    {author: "Henry David Thoreau", quote: "It is a characteristic of wisdom not to do desperate things."}, 
    {author: "Margaret Thatcher", quote: "If you set out to be liked, you would be prepared to compromise on anything at any time, and you would achieve nothing."}, 
    {author: "Abraham Lincoln", quote: "I have always found that mercy bears richer fruits than strict justice."}, 
    {author: "Buddha", quote: "It is better to travel well than to arrive."}, 
    {author: "Will Durant", quote: "Science gives us knowledge, but only philosophy can give us wisdom."}, 
    {author: "Susan B. Anthony", quote: "Independence is happiness."}, 
    {author: "Arthur Conan Doyle", quote: "Whenever you have eliminated the impossible, whatever remains, however improbable, must be the truth."}, 
    {author: "Baltasar Graci\u00e1n", quote: "Without courage, wisdom bears no fruit."}, 
    {author: "Audre Lorde", quote: "When I dare to be powerful, to use my strength in the service of my vision, then it becomes less and less important whether I am afraid."}, 
    {author: "John Burroughs", quote: "Wisdom cannot come by railroad or automobile or airplane or be hurried up by telegraph or telephone."}, 
    {author: "Norman Vincent Peale", quote: "Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy."}, 
    {author: "William Shakespeare", quote: "God has given you one face, and you make yourself another."}, 
    {author: "Brian Tracy", quote: "There is never enough time to do everything, but there is always enough time to do the most important thing."}, 
    {author: "Carl Lewis", quote: "Life is about timing."}, 
    {author: "Samuel Butler", quote: "Friendship is like money, easier made than kept."}, 
    {author: "Peter Drucker", quote: "Follow effective action with quiet reflection. From the quiet reflection will come even more effective action."}, 
    {author: "Mother Teresa", quote: "Peace begins with a smile."}, 
    {author: "Nelson Mandela", quote: "A good head and a good heart are always a formidable combination."}, 
    {author: "Confucius", quote: "The more you know yourself, the more you forgive yourself."}, 
    {author: "Wayne Dyer", quote: "You'll see it when you believe it."}, 
    {author: "John Lennon", quote: "Time you enjoyed wasting was not wasted."}, 
    {author: "James F. Byrnes", quote: "Friendship without self-interest is one of the rare and beautiful things of life."}, 
    {author: "Maya Angelou", quote: "When you learn, teach. When you get, give."}, 
    {author: "Sophocles", quote: "You win the victory when you yield to friends."}, 
    {author: "Aristotle", quote: "Friendship is essentially a partnership."}, 
    {author: "May Sarton", quote: "A garden is always a series of losses set against a few triumphs, like life itself."}, 
    {author: "Aesop", quote: "No act of kindness, no matter how small, is ever wasted."}, 
    {author: "Elizabeth Kenny", quote: "It's better to be a lion for a day than a sheep all your life."}, 
    {author: "Olivier Messiaen", quote: "One of the tests of leadership is the ability to recognize a problem before it becomes an emergency."}, 
    {author: "Friedrich Nietzsche", quote: "It is not a lack of love, but a lack of friendship that makes unhappy marriages."}, 
    {author: "Thomas Carlyle", quote: "By nature, man hates change; seldom will he quit his old home till it has actually fallen around his ears."}, 
    {author: "Sun Tzu", quote: "You have to believe in yourself."}, 
    {author: "Helen Keller", quote: "Never bend your head. Always hold it high. Look the world right in the eye."}, 
    {author: "Dalai Lama", quote: "I find hope in the darkest of days, and focus in the brightest. I do not judge the universe."}, 
    {author: "Saul Alinsky", quote: "As an organizer I start from where the world is, as it is, not as I would like it to be."}, 
    {author: "Aristotle", quote: "The energy of the mind is the essence of life."}, 
    {author: "Bruce Lee", quote: "Mistakes are always forgivable, if one has the courage to admit them."}, 
    {author: "Heraclitus", quote: "You cannot step twice into the same river, for other waters are continually flowing in."}, 
    {author: "Alexander Pope", quote: "Blessed is the man who expects nothing, for he shall never be disappointed."}, 
    {author: "Princess Diana", quote: "Only do what your heart tells you."}, 
    {author: "Henry David Thoreau", quote: "Ignorance and bungling with love are better than wisdom and skill without."}, 
    {author: "Bruce Lee", quote: "Love is like a friendship caught on fire. In the beginning a flame, very pretty, often hot and fierce, but still only light and flickering. As love grows older, our hearts mature and our love becomes as coals, deep-burning and unquenchable."}, 
    {author: "Friedrich Nietzsche", quote: "Rejoicing in our joy, not suffering over our suffering, makes someone a friend."}, 
    {author: "Bruce Lee", quote: "A wise man can learn more from a foolish question than a fool can learn from a wise answer."}, 
    {author: "Albert Einstein", quote: "Feeling and longing are the motive forces behind all human endeavor and human creations."}, 
    {author: "Isocrates", quote: "The noblest worship is to make yourself as good and as just as you can."}, 
    {author: "William Arthur Ward", quote: "Do more than dream: work."}, 
    {author: "Ansel Adams", quote: "In wisdom gathered over time I have found that every experience is a form of exploration."}, 
    {author: "Marcus Aurelius", quote: "He who lives in harmony with himself lives in harmony with the world."}, 
    {author: "Fran\u00e7ois de La Rochefoucauld", quote: "A true friend is the greatest of all blessings, and that which we take the least care of all to acquire."}, 
    {author: "Alan Watts", quote: "We cannot be more sensitive to pleasure without being more sensitive to pain."}, 
    {author: "Bernice Reagon", quote: "Life's challenges are not supposed to paralyze you, they're supposed to help you discover who you are."}, 
    {author: "Bob Newhart", quote: "All I can say about life is, Oh God, enjoy it!"}, 
    {author: "Mother Teresa", quote: "We shall never know all the good that a simple smile can do."}, 
    {author: "Oscar Wilde", quote: "Laughter is not at all a bad beginning for a friendship, and it is far the best ending for one."}, 
    {author: "Ralph Waldo Emerson", quote: "The only way to have a friend is to be one."}, 
    {author: "Mariella Frostrup", quote: "Every friendship goes through ups and downs. Dysfunctional patterns set in; external situations cause internal friction; you grow apart and then bounce back together."}, 
    {author: "Mark Twain", quote: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do."}, 
    {author: "Thomas Carlyle", quote: "Permanence, perseverance and persistence in spite of all obstacles, discouragements, and impossibilities: It is this, that in all things distinguishes the strong soul from the weak."}, 
    {author: "Richard Bach", quote: "The mark of your ignorance is the depth of your belief in injustice and tragedy. What the caterpillar calls the end of the world, the Master calls the butterfly."}, 
    {author: "Ralph Waldo Emerson", quote: "Nature is a mutable cloud which is always and never the same."}, 
    {author: "Annie Dillard", quote: "How we spend our days is, of course, how we spend our lives."}, 
    {author: "Aristotle", quote: "In all things of nature there is something of the marvelous."}, 
    {author: "Ralph Waldo Emerson", quote: "Most of the shadows of life are caused by standing in our own sunshine."}, 
    {author: "Douglas Adams", quote: "We are stuck with technology when what we really want is just stuff that works."}, 
    {author: "Elizabeth Browning", quote: "Love doesn't make the world go round; love is what makes the ride worthwhile."}, 
    {author: "James Oppenheim", quote: "The foolish man seeks happiness in the distance, the wise grows it under his feet."}, 
    {author: "Barbara Bush", quote: "Value your friendship. Value your relationships."}, 
    {author: "Marie Curie", quote: "I never see what has been done; I only see what remains to be done."}, 
    {author: "William Shakespeare", quote: "We know what we are but know not what we may be."}, 
    {author: "William Burroughs", quote: "Your mind will answer most questions if you learn to relax and wait for the answer."}, 
    {author: "Thomas Edison", quote: "I have not failed. I've just found 10,000 ways that won't work."}, 
    {author: "Ezra Stiles", quote: "A monarchy conducted with infinite wisdom and infinite benevolence is the most perfect of all possible governments."}, 
    {author: "Douglas Coupland", quote: "TV and the Internet are good because they keep stupid people from spending too much time out in public."}, 
    {author: "Mark Twain", quote: "There are basically two types of people. People who accomplish things, and people who claim to have accomplished things. The first group is less crowded."}, 
    {author: "Buddha", quote: "Holding on to anger is like grasping a hot coal with the intent of throwing it at someone else; you are the one who gets burned."}, 
    {author: "Richard Bach", quote: "Learning is finding out what you already know."}, 
    {author: "Clay Shirky", quote: "Communications tools don't get socially interesting until they get technologically boring."}, 
    {author: "Isaac Asimov", quote: "The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom."}, 
    {author: "Maya Angelou", quote: "I believe that every person is born with talent."}, 
    {author: "Sam Walton", quote: "There is only one boss. The customer. And he can fire everybody in the company from the chairman on down, simply by spending his money somewhere else."}, 
    {author: "James Gleick", quote: "As a technology, the book is like a hammer. That is to say, it is perfect: a tool ideally suited to its task. Hammers can be tweaked and varied but will never go obsolete. Even when builders pound nails by the thousand with pneumatic nail guns, every household needs a hammer."}, 
    {author: "Percy Bysshe Shelley", quote: "Fear not for the future, weep not for the past."}, 
    {author: "Carl Lewis", quote: "Life is about timing."}, 
    {author: "Mark Twain", quote: "Kindness is the language which the deaf can hear and the blind can see."}, 
    {author: "Thomas Hardy", quote: "Time changes everything except something within us which is always surprised by change."}, 
    {author: "Sam Levenson", quote: "Don't watch the clock; do what it does. Keep going."}, 
    {author: "Babe Ruth", quote: "The way a team plays as a whole determines its success. You may have the greatest bunch of individual stars in the world, but if they don't play together, the club won't be worth a dime."}, 
    {author: "Robert Frost", quote: "The best way out is always through."}, 
    {author: "Franklin D. Roosevelt", quote: "When you come to the end of your rope, tie a knot and hang on."}, 
    {author: "Socrates", quote: "The greatest way to live with honor in this world is to be what we pretend to be."}, 
    {author: "Bruce Lee", quote: "To know oneself is to study oneself in action with another person."}, 
    {author: "Virgil", quote: "They can conquer who believe they can."}, 
    {author: "Bodhidharma", quote: "All know the way; few actually walk it."}, 
    {author: "William Arthur Ward", quote: "Four steps to achievement: Plan purposefully. Prepare prayerfully. Proceed positively. Pursue persistently."}, 
    {author: "John Steinbeck", quote: "If we could learn to like ourselves, even a little, maybe our cruelties and angers might melt away."}, 
    {author: "Henry David Thoreau", quote: "Many men go fishing all of their lives without knowing that it is not fish they are after."}, 
    {author: "John Lennon", quote: "Time you enjoy wasting, was not wasted."}, 
    {author: "de La Rochefoucauld", quote: "In friendship as well as love, ignorance very often contributes more to our happiness than knowledge."}, 
    {author: "Abraham Lincoln", quote: "Always bear in mind that your own resolution to succeed is more important than any one thing."}, 
    {author: "Robert Frost", quote: "In three words I can sum up everything I've learned about life: it goes on."}, 
    {author: "Johann Wolfgang von Goethe", quote: "Wherever a man may happen to turn, whatever a man may undertake, he will always end up by returning to the path which nature has marked out for him."}, 
    {author: "Albert Einstein", quote: "One may say the eternal mystery of the world is its comprehensibility."}, 
    {author: "Confucius", quote: "When you meet someone better than yourself, turn your thoughts to becoming his equal. When you meet someone not as good as you are, look within and examine your own self."}, 
    {author: "Mother Teresa", quote: "If you can't feed a hundred people, then feed just one."}, 
    {author: "Johann Wolfgang von Goethe", quote: "Knowing is not enough; we must apply. Willing is not enough; we must do."}, 
    {author: "Confucius", quote: "When you see a man of worth, think of how you may emulate him. When you see one who is unworthy, examine yourself."}, 
    {author: "Richard Whately", quote: "Lose an hour in the morning, and you will spend all day looking for it."}, 
    {author: "Dale Turner", quote: "Some of the best lessons we ever learn are learned from past mistakes. The error of the past is the wisdom and success of the future."}, 
    {author: "Laozi", quote: "He who conquers others is strong; He who conquers himself is mighty."}, 
    {author: "Ralph Waldo Emerson", quote: "Imagination is not a talent of some men but is the health of every man."}, 
    {author: "Jean-Paul Sartre", quote: "Freedom is what you do with what's been done to you."}, 
    {author: "Seren Kierkegaard", quote: "Once you label me you negate me."}, 
    {author: "John Wooden", quote: "You can't let praise or criticism get to you. It's a weakness to get caught up in either one."}, 
    {author: "Ralph Waldo Emerson", quote: "The invariable mark of wisdom is to see the miraculous in the common."}, 
    {author: "John Burroughs", quote: "The smallest deed is better than the greatest intention."}, 
    {author: "Francis Bacon", quote: "It is impossible to love and to be wise."}, 
    {author: "Plotinus", quote: "Knowledge has three degrees: opinion, science, illumination. The means or instrument of the first is sense; of the second, dialectic; of the third, intuition."}, 
    {author: "Charles F. Kettering", quote: "One fails forward toward success."}, 
    {author: "Pierre-Auguste Renoir", quote: "The pain passes, but the beauty remains."}, 
    {author: "Lord Byron", quote: "Friendship is Love without his wings!"}, 
    {author: "Billie Armstrong", quote: "Our passion is our strength."}, 
    {author: "Buddha", quote: "It is better to travel well than to arrive."}, 
    {author: "Miguel de Cervantes", quote: "Those who will play with cats must expect to be scratched."}, 
    {author: "Mark Twain", quote: "Always tell the truth. That way, you don't have to remember what you said."}, 
    {author: "Richard Bach", quote: "Don't believe what your eyes are telling you. All they show is limitation. Look with your understanding, find out what you already know, and you'll see the way to fly."}, 
    {author: "Walt Whitman", quote: "I have learned that to be with those I like is enough."}, 
    {author: "Epictetus", quote: "The key is to keep company only with people who uplift you, whose presence calls forth your best."}, 
    {author: "William Shakespeare", quote: "All the world is a stage, And all the men and women merely players. They have their exits and entrances; Each man in his time plays many parts."}, 
    {author: "W. H. Auden", quote: "To choose what is difficult all one's days, as if it were easy, that is faith."}, 
    {author: "Laurence J. Peter", quote: "If you don't know where you are going, you will probably end up somewhere else."}, 
    {author: "Agatha Christie", quote: "Good advice is always certain to be ignored, but that's no reason not to give it."}, 
    {author: "Henry James", quote: "Three things in human life are important. The first is to be kind. The second is to be kind. The third is to be kind."}, 
    {author: "Abraham Lincoln", quote: "No man has a good enough memory to be a successful liar."}, 
    {author: "Pablo Picasso", quote: "Everything you can imagine is real."}, 
    {author: "Anne Bradstreet", quote: "If we had no winter, the spring would not be so pleasant; if we did not sometimes taste of adversity, prosperity would not be so welcome."}, 
    {author: "Tony Robbins", quote: "The way we communicate with others and with ourselves ultimately determines the quality of our lives."}, 
    {author: "Marcel Proust", quote: "Let us be grateful to people who make us happy; they are the charming gardeners who make our souls blossom."}, 
    {author: "Alexander Pope", quote: "Never find fault with the absent."}, 
    {author: "Ralph Waldo Emerson", quote: "A man's growth is seen in the successive choirs of his friends"}, 
    {author: "Douglas MacArthur", quote: "It is fatal to enter any war without the will to win it."}, 
    {author: "Laozi", quote: "The key to growth is the introduction of higher dimensions of consciousness into our awareness."}, 
    {author: "Friedrich Nietzsche", quote: "There is more wisdom in your body than in your deepest philosophy."}, 
    {author: "Plato", quote: "Bodily exercise, when compulsory, does no harm to the body; but knowledge which is acquired under compulsion obtains no hold on the mind."}, 
    {author: "Oprah Winfrey", quote: "Don't settle for a relationship that won't let you be yourself."}, 
    {author: "Kahlil Gibran", quote: "Let there be no purpose in friendship save the deepening of the spirit."}, 
    {author: "Christopher Reeve", quote: "What makes Superman a hero is not that he has power, but that he has the wisdom and the maturity to use the power wisely. From an acting point of view, that's how I approached the part."}, 
    {author: "Ambrose Bierce", quote: "The gambling known as business looks with austere disfavor upon the business known as gambling."}, 
    {author: "Pat Riley", quote: "Courage is not the absence of fear, but simply moving on with dignity despite that fear."}, 
    {author: "Norman Cousins", quote: "Never deny a diagnosis but do deny the negative verdict that may go with it."}, 
    {author: "Arthur C. Clarke", quote: "Any sufficiently advanced technology is equivalent to magic."}, 
    {author: "Marian Wright Edelman", quote: "You really can change the world if you care enough."}, 
    {author: "Tom Peters", quote: "Formula for success: under promise and over deliver."}, 
    {author: "Oscar Wilde", quote: "The aim of life is self-development. To realize one's nature perfectly - that is what each of us is here for."}, 
    {author: "Albert Einstein", quote: "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle."}, 
    {author: "Ludwig van Beethoven", quote: "Music is a higher revelation than all wisdom and philosophy."}, 
    {author: "Laozi", quote: "He who is contented is rich."}, 
    {author: "John Wooden", quote: "Be true to yourself, help others, make each day your masterpiece, make friendship a fine art, drink deeply from good books - especially the Bible, build a shelter against a rainy day, give thanks for your blessings and pray for guidance every day."}, 
    {author: "Laurence J. Peter", quote: "You can always tell a real friend: when you've made a fool of yourself he doesn't feel you've done a permanent job."}, 
    {author: "Maya Angelou", quote: "Nothing will work unless you do."}, 
    {author: "James M. Beggs", quote: "Before you put on a frown, make absolutely sure there are no smiles available."}
]

document.addEventListener("DOMContentLoaded", function() {
    const quote = document.querySelector(".quotes-box__quote span");
    const author = document.querySelector(".quotes-box__author span");
    
    const randomQuoteInfo = quotes[parseInt(Math.random() * (quotes.length - 1))];
    
    quote.innerText = randomQuoteInfo.quote;
    author.innerText = randomQuoteInfo.author;
});
